config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :reservation, only: %i(new create edit update destroy) do
    resources :card, except: %i(index)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	belongs_to :reservation
	validates :title, length: { in: 1..255 }
  validates :memo,  length: { maximum: 1000 }
end

app/models/contractor.rb
class Contractor < ApplicationRecord
	# has_many :reservations
	# has_many :orderers, through => :reservations
end

app/models/orderer.rb
class Orderer < ApplicationRecord
	# has_many :reservations
	# has_many :contractor, :through => :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	# belongs_to :orderer
	# belongs_to :contractor
	  belongs_to :user
		has_many :cards, dependent: :destroy
	validates :title, length: { in: 1 ..255 }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reservation,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable
    validates :name, presence: true, length: { maximum: 20 }
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
	before_action :set_card,only: %i(show edit update destroy)
    def new
			@card = Card.new
			@reservation = Reservation.find_by(id: params[:reservation_id])
		end

		def create
			@card = Card.new(card_params)
			if @card.save
				redirect_to :root
			else
				render action: :new
			end
		end

		def show
			render 'top'
		end

		def edit
			@reservations = Reservation.where(user: current_user)

		end

		def update
			if @card.update(card_params)
				redirect_to :root
			else
				render action: :edit
			end
		end

		def destroy
			@card.destroy
			redirect_to :root
		end
		
		
	
		private
			def card_params
				params.require(:card).permit(:title, :memo, :reservation_id)
			end

			def set_card
				@card = Card.find_by(id:params[:id])
			end
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
	before_action :set_reservation,only: %i(edit update destroy)

	def new
		@reservation = Reservation.new
	end
	
	def create
		 @reservation = Reservation.new(reservation_params)
		 if @reservation.save
		 	redirect_to :root
		# else
		# 	render action: :new
		 end
	end

	def edit
	end

	def update
		@reservation = Reservation.find_by(id:params[:id])
		if @reservation.update(reservation_params)
			redirect_to :root
		else
			render action: :edit
		end
	end

	def destroy
		@reservation.destroy
		redirect_to :root
	end

	private
		def reservation_params
			params.require(:reservation).permit(:title).merge(user: current_user)
		end
		def set_reservation
			@reservation = Reservation.find_by(id: params[:id])
		end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @reservations = Reservation.where(user: current_user).order("created_at ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/card/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
			<div class="cardeditForm_memo">
        <label>リスト名</label>
        <%= select :card, :reservation_id, @reservations.map{ |l| [l.title, l.id] }, {}, { class: 'form-control' } %>
      </div>
      <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :reservation_id, value: @reservation.id %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardContents_reservationStatus">
        <div>リスト名</div>
        <div><%= @card.reservation.title %></div>
      </div>
			<div class="cardContents_btnArea">
        <%= link_to '編集する', edit_reservation_card_path(@card.reservation, @card), class: "edit_btn" %>
				<%= link_to '削除をする', reservation_card_path(@card.reservation, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" } %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>crafts man</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/header' if current_user %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partial/_header.html.erb
<header class="header">
  <nav class="nav">
    <ul class="header_menu">
      <li class="nav-link"><%= current_user.name %>さん</li>
      <li class="header_menu_title"><%= link_to "crafts man", root_path, class: "nav-link" %></li>
      <li>
        <ul class="header_menu_inner">

          <li>
            <%# ==========この行を編集する========== %>
            <%= link_to new_reservation_path, class: "nav-link" do %>

              <span class="mr-1">工程を作成</span>
              <i class="fas fa-edit"></i>
            <% end %>
          </li>

          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>
        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/reservation/edit.html.erb
<div class="reservationeditPage">
  <div class="container">
    <%= form_with model: @reservation, url: { action: :update }, html: { class: 'reservationForm' }, local: true do |f| %>
      <% if @reservation.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control reservationName", placeholder: "工程名" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/reservation/new.html.erb
<div class="reservationnewPage">
  <div class="container">
    <%= form_with model: @reservation, url: { action: :create }, class: "new_reservation", local: true do |f| %>
      <% if @reservation.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control reservationName", placeholder: "工程名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<div class="topPage">
  <div class="reservationWrapper">
    <% @reservations.each do |reservation| %>
      <div class="reservation">
        <div class="reservation_header">
          <h2 class="reservation_header_title"><%= reservation.title %></h2>
          <div class="reservation_header_action">
					  <%= link_to content_tag(:i, '', class: 'fas fa-trash'), reservation, method: :delete, data: { confirm: "#{reservation.title}を削除して大丈夫ですか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_reservation_path(reservation)) %>
          </div>
        </div>
				<div class="cardWrapper">
					<% reservation.cards.each do |card| %>
					  <%= link_to reservation_card_path(reservation, card), class:"cardDetail_link" do %>
							<div class="card">
								<h3 class="card_title"><%= card.title %></h3>
								<% if card.memo.size > 0 %>
									<div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
								<% end %>
							</div>
						<% end %>
					<% end %>
					
          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "さらにカードを追加", new_reservation_card_path(reservation), class: "addCard_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>